CREATE TABLE [dbo].[BankSlopeAngles]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Angle] INT NOT NULL,
	[Slope] DECIMAL(18,2) NOT NULL,
    CONSTRAINT [PK_BankSlopeAngles] PRIMARY KEY ([ID] ASC),

)
