CREATE TABLE [dbo].[ClimateDatabase]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[Territory] NVARCHAR(50) NOT NULL,
	[PostCode] NVARCHAR(50) NOT NULL,
	[East] INT NOT NULL,
	[North] INT NOT NULL,
	[Altitude] DECIMAL(18, 9) NOT NULL,
	[MeanMinJan] DECIMAL(18, 9) NOT NULL,
	[MeanMinFeb] DECIMAL(18, 9) NOT NULL,
	[MeanMinMar] DECIMAL(18, 9) NOT NULL,
	[MeanMinApr] DECIMAL(18, 9) NOT NULL,
	[MeanMinMay] DECIMAL(18, 9) NOT NULL,
	[MeanMinJun] DECIMAL(18, 9) NOT NULL,
	[MeanMinJul] DECIMAL(18, 9) NOT NULL,
	[MeanMinAug] DECIMAL(18, 9) NOT NULL,
	[MeanMinSep] DECIMAL(18, 9) NOT NULL,
	[MeanMinOct] DECIMAL(18, 9) NOT NULL,
	[MeanMinNov] DECIMAL(18, 9) NOT NULL,
	[MeanMinDec] DECIMAL(18, 9) NOT NULL,
	[MeanMaxJan] DECIMAL(18, 9) NOT NULL,
	[MeanMaxFeb] DECIMAL(18, 9) NOT NULL,
	[MeanMaxMar] DECIMAL(18, 9) NOT NULL,
	[MeanMaxApr] DECIMAL(18, 9) NOT NULL,
	[MeanMaxMay] DECIMAL(18, 9) NOT NULL,
	[MeanMaxJun] DECIMAL(18, 9) NOT NULL,
	[MeanMaxJul] DECIMAL(18, 9) NOT NULL,
	[MeanMaxAug] DECIMAL(18, 9) NOT NULL,
	[MeanMaxSep] DECIMAL(18, 9) NOT NULL,
	[MeanMaxOct] DECIMAL(18, 9) NOT NULL,
	[MeanMaxNov] DECIMAL(18, 9) NOT NULL,
	[MeanMaxDec] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallJan] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallFeb] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallMar] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallApr] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallMay] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallJun] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallJul] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallAug] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallSep] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallOct] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallNov] DECIMAL(18, 9) NOT NULL,
	[MeanTotalRainFallDec] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursJan] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursFeb] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursMar] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursApr] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursMay] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursJun] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursJul] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursAug] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursSep] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursOct] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursNov] DECIMAL(18, 9) NOT NULL,
	[MeanSunHoursDec] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysJan] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysFeb] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysMar] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysApr] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysMay] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysJun] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysJul] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysAug] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysSep] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysOct] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysNov] DECIMAL(18, 9) NOT NULL,
	[MeanRainDaysDec] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedJan] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedFeb] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedMar] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedApr] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedMay] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedJun] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedJul] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedAug] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedSep] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedOct] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedNov] DECIMAL(18, 9) NOT NULL,
	[MeanWindSpeedDec] DECIMAL(18, 9) NOT NULL,
    CONSTRAINT [PK_ClimateDatabase] PRIMARY KEY ([ID] ASC)
)
