CREATE TABLE [dbo].[Crops] (
    [ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [FieldID]               INT             NOT NULL,
    [Year]                  INT             NOT NULL,
    [CropTypeID]            INT             NULL,
    [FieldType]             INT             CONSTRAINT [DF_Crops_FieldType] DEFAULT ((1)) NOT NULL,
    [Variety]               NVARCHAR (100)  NULL,
    [OtherCropName]         NVARCHAR (128)  NULL,
    [CropInfo1]             INT             NULL,
    [CropInfo2]             INT             NULL,
    [SowingDate]            DATETIME2 (7)   NULL,
    [Yield]                 DECIMAL (18, 3) NULL,
    [CropGroupName]         NVARCHAR (120)  NULL,
    [Confirm]               BIT             CONSTRAINT [DF_Crops_Confirm] DEFAULT ((0)) NOT NULL,
    [PreviousGrass]         INT             NULL,
    [GrassHistory]          INT             NULL,
    [Comments]              NVARCHAR (512)  NULL,
    [Establishment]         INT             NULL,
    [LivestockType]         INT             NULL,
    [MilkYield]             DECIMAL (18, 3) CONSTRAINT [DF_Crops_MilkYield] DEFAULT ((0)) NULL,
    [ConcentrateUse]        DECIMAL (18, 3) CONSTRAINT [DF_Crops_ConcentrateUse] DEFAULT ((0)) NULL,
    [StockingRate]          DECIMAL (18, 3) CONSTRAINT [DF_Crops_StockingRate] DEFAULT ((0)) NULL,
    [DefoliationSequenceID] INT             NULL,
    [GrazingIntensity]      INT             CONSTRAINT [DF_Crops_GrazingIntensity] DEFAULT ((0)) NULL,
    [CropOrder]             INT             CONSTRAINT [DF_Crops_CropOrder] DEFAULT ((1)) NOT NULL,
    [SwardTypeID]           INT             NULL,
    [SwardManagementID]     INT             NULL,
    [PotentialCut]          INT             NULL,
    [CreatedOn]             DATETIME2       NULL DEFAULT GETDATE(), 
    [CreatedByID]           INT             NULL,
    [ModifiedOn]            DATETIME2    NULL,
    [ModifiedByID]          INT             NULL,
    [PreviousID]            INT             NULL,
    CONSTRAINT [PK_Crops] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_Crops_FieldID_Year_CropTypeID_CropOrder] UNIQUE ([FieldID], [Year], [CropTypeID], [CropOrder]),
    CONSTRAINT [FK_Crops_Fields] FOREIGN KEY ([FieldID]) REFERENCES [dbo].[Fields] ([ID]),
    CONSTRAINT [FK_Crops_Users_CreatedBy] FOREIGN KEY ([CreatedByID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_Crops_Users_ModifiedBy] FOREIGN KEY ([ModifiedByID]) REFERENCES [dbo].[Users] ([ID])
);



