CREATE TABLE [dbo].[FarmsNVZ]
(
	[ID] INT NOT NULL IDENTITY(1,1), 
    [FarmID] INT NOT NULL, 
    [NVZProgrammeID] INT NOT NULL,
    [NVZProgrammeName] NVARCHAR(128) NOT NULL,
    CONSTRAINT [PK_FarmsNVZ] PRIMARY KEY ([ID] ASC),
    CONSTRAINT [FK_FarmsNVZ_Farms] FOREIGN KEY([FarmID]) REFERENCES [dbo].[Farms] ([ID]),
)
