CREATE TABLE [dbo].[FertiliserManures]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[ManagementPeriodID] INT NOT NULL,
	[ApplicationDate] DATETIME NOT NULL,
	[ApplicationRate] INT NOT NULL,
	[Confirm] BIT NULL,
	[N] DECIMAL(18, 3) NOT NULL,
	[P2O5] DECIMAL(18, 3) NOT NULL,
	[K2O] DECIMAL(18, 3) NOT NULL,
	[MgO] DECIMAL(18, 3) NOT NULL,
	[SO3] DECIMAL(18, 3) NOT NULL,
	[Na2O] DECIMAL(18, 3) NOT NULL,
	[NFertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[P2O5FertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[K2OFertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[MgOFertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[SO3FertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[Na2OFertAnalysisPercent] DECIMAL(18, 3) NOT NULL,
	[Lime] DECIMAL(18, 3) NOT NULL,
	[NH4N] DECIMAL(18, 3) NOT NULL,
	[NO3N] DECIMAL(18, 3) NOT NULL,
	[CreatedOn] DATETIME2 NULL DEFAULT GETDATE(), 
    [CreatedByID] INT NULL, 
    [ModifiedOn] DATETIME2 NULL, 
    [ModifiedByID] INT NULL,
	CONSTRAINT [PK_FertiliserManures] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FertiliserManures_ManagementPeriods] FOREIGN KEY([ManagementPeriodID]) REFERENCES [dbo].[ManagementPeriods] ([ID]),
	 CONSTRAINT [FK_FertiliserManures_Users_CreatedBy] FOREIGN KEY([CreatedByID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_FertiliserManures_Users_ModifiedBy] FOREIGN KEY([ModifiedByID]) REFERENCES [dbo].[Users] ([ID])
)	
