CREATE TABLE [dbo].[MannerApplications]
(
	[ID]	INT IDENTITY(1,1) NOT NULL,
	[FieldID]  INT           NULL,
	[ManureTypeID] INT NULL,
	[ApplicationDate] DATETIME NULL,
	[ApplicationRate] DECIMAL(18, 3) NULL,
	[ApplicationMethodID] INT NULL,
	[IncorporationID] INT NULL,
	[IncroporationDelayID] INT NULL,
	[CropNUptake] DECIMAL(18, 3) NULL,
	[SoilDrainageEndDate] DATETIME NULL,
	[RainfallPostApp] DECIMAL(18, 1) NULL,
	[WindspeedID] INT NULL,
	[RainfallWithin6HoursID] INT NULL,
	[MoistureID] INT NULL,
	[DryMatter] DECIMAL(18, 2) NULL,
	[TotalN] DECIMAL(18, 2) NULL,
	[AmmoniumN] DECIMAL(18, 2) NULL,
	[UricAcid] DECIMAL(18, 2) NULL,
	[NitrateN] DECIMAL(18, 2) NULL,
	[TotalP2O5] DECIMAL(18, 2) NULL,
	[TotalK2O] DECIMAL(18, 2) NULL,
	[TotalMgO] DECIMAL(18, 2) NULL,
	[TotalSO3] DECIMAL(18, 2) NULL,
    CONSTRAINT [PK_MannerApplications] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MannerApplications_Fields] FOREIGN KEY([FieldID]) REFERENCES [dbo].[Fields] ([ID]),
	CONSTRAINT [FK_MannerApplications_ManureTypes_ManureTypeID] FOREIGN KEY([ManureTypeID]) REFERENCES [dbo].[ManureTypes] ([ID]),
	CONSTRAINT [FK_MannerApplications_ApplicationMethods_ApplicationMethodID] FOREIGN KEY([ApplicationMethodID]) REFERENCES [dbo].[ApplicationMethods] ([ID]),
	CONSTRAINT [FK_MannerApplications_Incorporations_IncorporationID] FOREIGN KEY([IncorporationID]) REFERENCES [dbo].[IncorporationMethods] ([ID]),
	CONSTRAINT [FK_MannerApplications_IncroporationDelays_IncroporationDelayID] FOREIGN KEY([IncroporationDelayID]) REFERENCES [dbo].[IncorporationDelays] ([ID]),
	CONSTRAINT [FK_MannerApplications_Windspeeds_WindspeedID] FOREIGN KEY([WindspeedID]) REFERENCES [dbo].[Windspeeds] ([ID]),
	CONSTRAINT [FK_MannerApplications_RainsWithinSixHours_RainfallWithin6HoursID] FOREIGN KEY([RainfallWithin6HoursID]) REFERENCES [dbo].[RainsWithinSixHours] ([ID]),
	CONSTRAINT [FK_MannerApplications_TopsoilMoistures_MoistureID] FOREIGN KEY([MoistureID]) REFERENCES [dbo].[TopsoilMoistures] ([ID])
)
