CREATE TABLE [dbo].[MannerEstimations]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[FarmName]     NVARCHAR(250) NOT NULL,
	[CountryID]    INT  NOT NULL,
	[Postcode]     NVARCHAR (50)   NOT NULL,
	[AverageAnuualRainfall]     INT  NOT NULL,
	[FieldName]    NVARCHAR(50) NOT NULL,
	[IsWithinNVZ]  BIT NOT NULL,
	[NVZProgrammeID] INT NULL,
	[TopSoilID]   INT NOT NULL,
	[SubSoilID]   INT NOT NULL,
	[CropTypeID]   INT NOT  NULL,
	[MannerCropTypeID]   INT NOT  NULL,
	[SowingDate]         DATETIME2 NULL,
    [CreatedOn] DATETIME2 NULL CONSTRAINT DF_MannerEstimations_CreatedOn DEFAULT GETDATE(), 
    [CreatedByID] INT NULL,
	[ModifiedOn] DATETIME2 NULL,
	[ModifiedByID] INT NULL,
	CONSTRAINT [PK_MannerEstimations] PRIMARY KEY ([ID] ASC),
	CONSTRAINT [FK_MannerEstimations_Countries] FOREIGN KEY([CountryID]) REFERENCES [dbo].[Countries] ([ID]),
)
