CREATE TABLE [dbo].[MannerEstimations]
(
	[ID] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(250) NOT NULL,
	[OrganisationID] UNIQUEIDENTIFIER NOT NULL,
	[FarmName]     NVARCHAR(250) NOT NULL,
	[CountryID]    INT  NOT NULL,
	[Postcode]     NVARCHAR (50)   NOT NULL,
	[AverageAnuualRainfall]     INT  NOT NULL,
	[FieldName]    NVARCHAR(50) NOT NULL,
	[IsWithinNVZ]  BIT NOT NULL,
	[RegisteredOrganicProducer] BIT NOT NULL CONSTRAINT DF_MannerEstimations_RegisteredOrganicProducer DEFAULT 0,
	[TopSoilID]   INT NOT NULL,
	[SubSoilID]   INT NOT NULL,
	[CropTypeID]   INT NOT  NULL,
	[MannerCropTypeID]   INT NOT  NULL,
	[SowingDate]         DATETIME2 NULL,
	[NitrogenProductId] INT NOT NULL,
    [PhosphateProductId] INT NOT NULL,
    [PotashProductId] INT NOT NULL,
    [NitrogenProductName] NVARCHAR(100) NOT NULL,
    [PhosphateProductName] NVARCHAR(100) NOT NULL,
    [PotashProductName] NVARCHAR(100) NOT NULL,
    [NitrogenProductPrice] INT NOT NULL,
    [PhosphateProductPrice] INT NOT NULL,
    [PotashProductPrice] INT NOT NULL,
      [NitrogenPrice] DECIMAL(18,2) NOT NULL,
    [PhosphatePrice] DECIMAL(18,2) NOT NULL,
    [PotashPrice] DECIMAL(18,2) NOT NULL,
	[CalculateBasedOnNutrientPrice] BIT NOT NULL CONSTRAINT DF_MannerEstimations_CalculateBasedOnNutrientPrice DEFAULT 1,
    [CreatedOn] DATETIME2 NULL CONSTRAINT DF_MannerEstimations_CreatedOn DEFAULT GETDATE(), 
    [CreatedByID] INT NULL,
	[ModifiedOn] DATETIME2 NULL,
	[ModifiedByID] INT NULL,
	CONSTRAINT [PK_MannerEstimations] PRIMARY KEY ([ID] ASC),
    CONSTRAINT [UQ_MannerEstimations_Name_OrganisationID] UNIQUE ([Name], [OrganisationID]),
	CONSTRAINT [FK_MannerEstimations_Countries] FOREIGN KEY([CountryID]) REFERENCES [dbo].[Countries] ([ID]),
	CONSTRAINT [FK_MannerEstimations_Organisations] FOREIGN KEY([OrganisationID]) REFERENCES [dbo].[Organisations] ([ID])
)
