CREATE TABLE [dbo].[MannerApplications]
(
	[ID]	INT IDENTITY(1,1) NOT NULL,
	[FieldID]  INT           NULL,
    [Year]     INT           NULL,
	[ManureTypeID] INT NULL,
	[ApplicationDate] DATETIME NULL,
	[ApplicationRate] DECIMAL(18, 2) NULL,
	[ApplicationMethodID] INT NULL,
	[IncorporationID] INT NULL,
	[IncroporationDelayID] INT NULL,
	[CropNUptake] INT NULL,
	[SoilDrainageEndDate] DATETIME NULL,
	[RainfallAfterApp] INT NULL,
	[WindspeedID] INT NULL,
	[RainfallWithin6HoursID] INT NULL,
	[MoistureID] INT NULL,
	[DryMatter] DECIMAL(18, 2) NULL,
	[TotalN] DECIMAL(18, 2) NULL,
	[AmmoniumN] DECIMAL(18, 2) NULL,
	[UricAcid] DECIMAL(18, 2) NULL,
	[NitrateN] DECIMAL(18, 2) NULL,
	[P] DECIMAL(18, 2) NULL,
	[K] DECIMAL(18, 2) NULL,
	[Mg] DECIMAL(18, 2) NULL,
	[S] DECIMAL(18, 2) NULL,
    CONSTRAINT [PK_MannerApplications] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MannerApplications_Fields] FOREIGN KEY([FieldID]) REFERENCES [dbo].[Fields] ([ID]),
	CONSTRAINT [FK_MannerApplications_ManureTypes] FOREIGN KEY([ManureTypeID]) REFERENCES [dbo].[ManureTypes] ([ID]),
	CONSTRAINT [FK_MannerApplications_ApplicationMethods] FOREIGN KEY([ApplicationMethodID]) REFERENCES [dbo].[ApplicationMethods] ([ID]),
	CONSTRAINT [FK_MannerApplications_Incorporations] FOREIGN KEY([IncorporationID]) REFERENCES [dbo].[Incorporations] ([ID]),
	CONSTRAINT [FK_MannerApplications_IncroporationDelays] FOREIGN KEY([IncroporationDelayID]) REFERENCES [dbo].[IncorporationDelays] ([ID]),
	CONSTRAINT [FK_MannerApplications_Windspeeds] FOREIGN KEY([WindspeedID]) REFERENCES [dbo].[Windspeeds] ([ID]),
	CONSTRAINT [FK_MannerApplications_RainsWithinSixHours] FOREIGN KEY([RainfallWithin6HoursID]) REFERENCES [dbo].[RainsWithinSixHours] ([ID]),
	CONSTRAINT [FK_MannerApplications_Moistures] FOREIGN KEY([MoistureID]) REFERENCES [dbo].[Moistures] ([ID])
)
