CREATE TABLE [dbo].[MannerEstimationApplications]
(
	[ID] INT NOT NULL Identity(1,1),
    [MannerEstimationID] INT NOT NULL,
	[ManureTypeID]         INT NOT NULL,
	[ApplicationDate]          DATETIME        NOT NULL,
	[N]                        DECIMAL (18, 3) NOT NULL,
    [P2O5]                     DECIMAL (18, 3) NOT NULL,
    [K2O]                      DECIMAL (18, 3) NOT NULL,
    [MgO]                      DECIMAL (18, 3) NOT NULL,
    [SO3]                      DECIMAL (18, 3) NOT NULL,
    [DryMatterPercent]         DECIMAL (18, 2) NOT NULL,
    [UricAcid]                 DECIMAL (18, 2) NOT NULL,    
    [ApplicationRate]          DECIMAL(18, 1)  NOT NULL,
	[AreaSpread]               DECIMAL (18, 3) NULL,
    [ManureQuantity]           DECIMAL (18, 3) NULL,
	[IncorporationMethodID]    INT             NOT NULL,
    [IncorporationDelayID]     INT             NOT NULL,
	[WindspeedID]              INT             NOT NULL,
    [RainfallWithinSixHoursID] INT             NOT NULL,
    [MoistureID]               INT             NOT NULL,
    [AutumnCropNitrogenUptake] INT             NOT NULL,
	[EndOfDrainageDate]        DATETIME        NOT NULL,
    [RainfallPostApplication]  INT             NOT NULL,
    [CreatedOn] DATETIME2 NULL CONSTRAINT DF_MannerEstimationApplications_CreatedOn DEFAULT GETDATE(), 
    [CreatedByID] INT NULL,
	[ModifiedOn] DATETIME2 NULL,
	[ModifiedByID] INT NULL,
	CONSTRAINT [PK_MannerEstimationApplications] PRIMARY KEY ([ID] ASC),
	CONSTRAINT [FK_MannerEstimationApplications_MannerEstimationID] FOREIGN KEY([MannerEstimationID]) REFERENCES [dbo].[MannerEstimations] ([ID]),        
)
