CREATE TABLE [dbo].[ManureTypes]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50)  NULL,
	[Country] INT NULL,
	[IsLiquid] BIT  NULL,
	[DryMatter] DECIMAL(18,2) NULL,
	[TotalN] DECIMAL(18,2) NULL,
	[NH4N] DECIMAL(18,2) NULL,
	[Uric] DECIMAL(18,2) NULL,
	[NO3N] DECIMAL(18,2) NULL,
	[P2O5] DECIMAL(18,2) NULL,
	[K2O] DECIMAL(18,2) NULL,
	[SO3] DECIMAL(18,2) NULL,
	[MgO] DECIMAL(18,2) NULL,
	CONSTRAINT [PK_ManureTypes] PRIMARY KEY CLUSTERED ([ID] ASC),
)
