CREATE TABLE [dbo].[NutrientsLoadingLiveStocks] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [FarmID]           INT             NOT NULL,
    [LiveStockGroupID] INT             NOT NULL,
    [LiveStockTypeID]  INT             NULL,
    [Units]            DECIMAL (18, 3) NULL,
    [NByUnit]          DECIMAL (18, 3) NULL,
    [TotalNProduced]   DECIMAL (18, 3) NULL,
    [Occupancy]        INT             NULL,
    [PByUnit]          DECIMAL (18)    NULL,
    [TotalPProduced]   INT             NULL,
    [Jan]              INT             NULL,
    [Feb]              INT             NULL,
    [Mar]              INT             NULL,
    [Apr]              INT             NULL,
    [May]              INT             NULL,
    [June]             INT             NULL,
    [July]             INT             NULL,
    [Aug]              INT             NULL,
    [Sep]              INT             NULL,
    [Oct]              INT             NULL,
    [Nov]              INT             NULL,
    [Dec]              INT             NULL,    
    [CreatedOn]        DATETIME2       NULL DEFAULT GETDATE(), 
    [CreatedByID]      INT             NULL, 
    [ModifiedOn]       DATETIME2       NULL, 
    [ModifiedByID]     INT             NULL,
    CONSTRAINT [PK_NutrientsLoadingLiveStocks] PRIMARY KEY ([ID] ASC),
    CONSTRAINT [FK_NutrientsLoadingLiveStocks_Farms] FOREIGN KEY ([FarmID]) REFERENCES [Farms]([ID])
);

