CREATE TABLE [dbo].[OrganicManures]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ManagementPeriodID] [int] NOT NULL,
	[ManureTypeID] [int] NOT NULL,
	[ApplicationDate] [datetime] NULL,
	[Confirm] [bit] NULL,
	[N] [decimal](18, 3) NOT NULL,
	[P2O5] [decimal](18, 3) NOT NULL,
	[K2O] [decimal](18, 3) NOT NULL,
	[MgO] [decimal](18, 3) NOT NULL,
	[SO3] [decimal](18, 3) NOT NULL,
	[AvailableN] [decimal](18, 3) NOT NULL,
	[ApplicationRate] [int] NOT NULL,
	[DryMatterPercent] [decimal](18, 2) NOT NULL,
	[UricAcid] [decimal](18, 2) NOT NULL,
	[EndOfDrain] [datetime] NULL,
	[Rainfall] [int] NOT NULL,
	[AreaSpread] [decimal](18, 3) NULL,
	[ManureQuantity] [decimal](18, 3) NULL,
	[ApplicationMethodID] [int] NOT NULL,
	[IncorporationMethodID] [int] NOT NULL,
	[IncorporationDelayID] [int] NOT NULL,
	[NH4N] [decimal](18, 3) NOT NULL,
	[NO3N] [decimal](18, 3) NOT NULL,
	[AvailableP2O5] [decimal](18, 3) NULL,
	[AvailableK2O] [decimal](18, 3) NULL,
	[WindspeedID] [int] NULL,
	[RainfallWithinSixHoursID] [int] NULL,
	[MoistureID] [int] NULL,
	[AutumnCropNitrogenUptake] [decimal](5, 2) NOT NULL CONSTRAINT DF_OrganicManures_AutumnCropNitrogenUptake DEFAULT (0),
	[CreatedOn] DATETIME2 NULL DEFAULT GETDATE(), 
    [CreatedByID] INT NULL, 
    [ModifiedOn] DATETIME2 NULL, 
    [ModifiedByID] INT NULL,
	CONSTRAINT [PK_OrganicManures] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_OrganicManures_ManagementPeriods] FOREIGN KEY([ManagementPeriodId]) REFERENCES [dbo].[ManagementPeriods] ([ID]),
	CONSTRAINT [FK_OrganicManures_ManureTypes] FOREIGN KEY([ManureTypeID]) REFERENCES [dbo].[ManureTypes] ([ID]),
	CONSTRAINT [FK_OrganicManures_ApplicationMethods] FOREIGN KEY([ApplicationMethodID]) REFERENCES [dbo].[ApplicationMethods] ([ID]),
	CONSTRAINT [FK_OrganicManures_IncorporationMethods] FOREIGN KEY([IncorporationMethodID]) REFERENCES [dbo].[IncorporationMethods] ([ID]),
	CONSTRAINT [FK_OrganicManures_IncorporationDelays] FOREIGN KEY([IncorporationDelayID]) REFERENCES [dbo].[IncorporationDelays] ([ID]),
	CONSTRAINT [FK_OrganicManures_Windspeeds] FOREIGN KEY([WindspeedID]) REFERENCES [dbo].[Windspeeds] ([ID]),
	CONSTRAINT [FK_OrganicManures_RainTypes] FOREIGN KEY([RainfallWithinSixHoursID]) REFERENCES [dbo].[RainTypes] ([ID]),
	CONSTRAINT [FK_OrganicManures_MoistureTypes] FOREIGN KEY([MoistureID]) REFERENCES [dbo].[MoistureTypes] ([ID]),
	 CONSTRAINT [FK_OrganicManures_Users_CreatedBy] FOREIGN KEY([CreatedByID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_OrganicManures_Users_ModifiedBy] FOREIGN KEY([ModifiedByID]) REFERENCES [dbo].[Users] ([ID])

)
