CREATE TABLE [dbo].[OrganicManures]
(
	[ID] [int]  NOT NULL IDENTITY(1,1),
	[ManagementPeriodID] [int] NOT NULL,	
	[ManureTypeID] [int] NOT NULL,
	[AppDate] [datetime] NULL,
	[Confirm] [bit] NULL,
	[N] [decimal](18, 3)  NOT NULL,
	[P2O5] [decimal](18, 3)  NOT NULL,
	[K2O] [decimal](18, 3)  NOT NULL,
	[MgO] [decimal](18, 3)  NOT NULL,
	[SO3] [decimal](18, 3)  NOT NULL,
	[AvailableN] [decimal](18, 3)  NOT NULL,
	[AppRate] [int]  NOT NULL,
	[DryMatterPercent] [int]  NOT NULL,
	[UricAcid] [int]  NOT NULL,
	[EndOfDrain] [datetime] NULL,
	[Rainfall] [int]  NOT NULL,
	[AreaSpread] [decimal](18, 3) NULL,
	[ManureQuantity] [decimal](18, 3) NULL,
	[ApplicationMethodID] [int]  NOT NULL,
	[IncroporationMethodID] [int]  NOT NULL,
	[IncroporationDelayID] [int]  NOT NULL,
	[NH4N] [decimal](18, 3)  NOT NULL,
	[NO3N] [decimal](18, 3)  NOT NULL,
	[AvailableP2O5] [decimal](18, 3) NULL,
	[AvailableK2O] [decimal](18, 3) NULL,
	[WindspeedID] INT NULL,
	[RainfallWithin6HoursID] INT NULL,
	[MoistureID] INT NULL,
	CONSTRAINT [PK_OrganicManures] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_OrganicManures_Fields] FOREIGN KEY([ManagementPeriodId]) REFERENCES [dbo].[ManagementPeriods] ([ID]),
	CONSTRAINT [FK_OrganicManures_ManureTypes_ManureTypeID] FOREIGN KEY([ManureTypeID]) REFERENCES [dbo].[ManureTypes] ([ID]),
	CONSTRAINT [FK_OrganicManures_ApplicationMethods_ApplicationMethodID] FOREIGN KEY([ApplicationMethodID]) REFERENCES [dbo].[ApplicationMethods] ([ID]),
	CONSTRAINT [FK_OrganicManures_IncorporationMethods_IncroporationMethodID] FOREIGN KEY([IncroporationMethodID]) REFERENCES [dbo].[IncorporationMethods] ([ID]),
	CONSTRAINT [FK_OrganicManures_IncroporationDelays_IncroporationDelayID] FOREIGN KEY([IncroporationDelayID]) REFERENCES [dbo].[IncorporationDelays] ([ID]),
	CONSTRAINT [FK_OrganicManures_Windspeeds_WindspeedID] FOREIGN KEY([WindspeedID]) REFERENCES [dbo].[Windspeeds] ([ID]),
	CONSTRAINT [FK_OrganicManures_RainTypes_RainfallWithin6HoursID] FOREIGN KEY([RainfallWithin6HoursID]) REFERENCES [dbo].[RainTypes] ([ID]),
	CONSTRAINT [FK_OrganicManures_MoistureTypes_MoistureID] FOREIGN KEY([MoistureID]) REFERENCES [dbo].[MoistureTypes] ([ID])

)
