CREATE TABLE [dbo].[Recommendations]
(
    [ID]                    INT             NOT NULL IDENTITY (1, 1),
    [ManagementPeriodID]    INT             NOT NULL,
    [CropN]                 DECIMAL(18,3)  NULL,
    [CropP2O5]              DECIMAL(18,3)  NULL,
    [CropK2O]               DECIMAL(18,3)  NULL,
    [CropMgO]               DECIMAL(18,3)  NULL,
    [CropSO3]               DECIMAL(18,3)  NULL,
    [CropNa2O]              DECIMAL(18,3)  NULL,
    [CropLime]              DECIMAL(18,3)  NULL,
    [ManureN]               DECIMAL(18,3)  NULL,
    [ManureP2O5]            DECIMAL(18,3)  NULL,
    [ManureK2O]             DECIMAL(18,3)  NULL,
    [ManureMgO]             DECIMAL(18,3)  NULL,
    [ManureSO3]             DECIMAL(18,3)  NULL,
    [ManureNa2O]            DECIMAL(18,3)  NULL,
    [ManureLime]            DECIMAL(18,3)  NULL,
    [FertilizerN]           DECIMAL(18,3)  NULL,
    [FertilizerP2O5]        DECIMAL(18,3)  NULL,
    [FertilizerK2O]         DECIMAL(18,3)  NULL,
    [FertilizerMgO]         DECIMAL(18,3)  NULL,
    [FertilizerSO3]         DECIMAL(18,3)  NULL,    
    [FertilizerNa2O]        DECIMAL(18,3)  NULL,
    [FertilizerLime]        DECIMAL(18,3)  NULL,
    [PH]                    NVARCHAR (30)  NULL,
    [SNSIndex]              NVARCHAR (30)  NULL,
    [PIndex]                NVARCHAR (30)  NULL,
    [KIndex]                NVARCHAR (30)  NULL,
    [MgIndex]               NVARCHAR (30)  NULL,
    [SIndex]                NVARCHAR (30)  NULL,
    [NaIndex]               NVARCHAR (30)  NULL,
    [NIndex]                NVARCHAR (30)  NULL,
    [NBalance]              INT  NULL,
    [PBalance]              INT  NULL,
    [KBalance]              INT  NULL,
    [MgBalance]             INT  NULL,
    [SBalance]              INT  NULL,
    [NaBalance]             INT  NULL,
    [LimeBalance]           INT  NULL,
    [Comments]              NVARCHAR (MAX) NULL,
    [CreatedOn]             DATETIME2      NULL DEFAULT GETDATE(), 
    [CreatedByID]           INT            NULL, 
    [ModifiedOn]            DATETIME2      NULL, 
    [ModifiedByID]          INT            NULL,
    [PreviousID]            INT            NULL,
    CONSTRAINT [PK_Recommendations] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Recommendations_ManagementPeriods] FOREIGN KEY([ManagementPeriodID]) REFERENCES [dbo].[ManagementPeriods] ([ID]),
    CONSTRAINT [FK_Recommendations_Users_CreatedBy] FOREIGN KEY([CreatedByID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_Recommendations_Users_ModifiedBy] FOREIGN KEY([ModifiedByID]) REFERENCES [dbo].[Users] ([ID]),

);


