CREATE TABLE [dbo].[StoreCapacities]
(
	[ID]	INT  IDENTITY (1, 1) NOT NULL,
	[FarmID] INT NOT NULL,
	[StoreName] NVARCHAR(128) NOT NULL,
	[MaterialStateID] INT NOT NULL,
	[StorageTypeID] INT  NULL,
	[SolidManureTypeID] INT  NULL,
	[Length] DECIMAL(18, 3) NULL,
	[Width] DECIMAL(18, 3) NULL,
	[Depth] DECIMAL(18, 3) NULL,
	[Circumference] DECIMAL(18, 3) NULL,
	[Diameter] DECIMAL(18, 3) NULL,
	[BankSlopeAngleID] INT  NULL,
	[IsCovered] BIT NULL,
	[CapacityVolume] DECIMAL(18, 3) NULL,
	[CapacityWeight] DECIMAL(18, 3) NULL,
	[SurfaceArea] DECIMAL(18, 3) NULL,
    [CreatedOn]             DATETIME2       NULL DEFAULT GETDATE(), 
    [CreatedByID]           INT             NULL,
    [ModifiedOn]            DATETIME2    NULL,
    [ModifiedByID]          INT             NULL,
    [PreviousID]            INT             NULL,
	CONSTRAINT [PK_StoreCapacities] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_StoreCapacities_Farms] FOREIGN KEY ([FarmID]) REFERENCES [Farms]([ID]),
    CONSTRAINT [FK_StoreCapacities_MaterialStates] FOREIGN KEY ([MaterialStateID]) REFERENCES [MaterialStates]([ID]),
    CONSTRAINT [FK_StoreCapacities_StorageTypes] FOREIGN KEY ([StorageTypeID]) REFERENCES [StorageTypes]([ID]),
    CONSTRAINT [FK_StoreCapacities_SolidManureTypes] FOREIGN KEY ([SolidManureTypeID]) REFERENCES [SolidManureTypes]([ID]),
    CONSTRAINT [FK_StoreCapacities_BankSlopeAngles] FOREIGN KEY ([BankSlopeAngleID]) REFERENCES [BankSlopeAngles]([ID]),	
    CONSTRAINT [FK_StoreCapacities_Users_CreatedBy] FOREIGN KEY ([CreatedByID]) REFERENCES [dbo].[Users] ([ID]),
    CONSTRAINT [FK_StoreCapacities_Users_ModifiedBy] FOREIGN KEY ([ModifiedByID]) REFERENCES [dbo].[Users] ([ID])
)
