--CREATE TABLE [dbo].[UserFarms]
--(
--	[UserID] INT NOT NULL,
--	[FarmID] INT NOT NULL,
--	[RoleID] INT NOT NULL,
--	CONSTRAINT [PK_UserFarms] PRIMARY KEY ([UserID],[FarmID] ASC),	
--	CONSTRAINT [FK_UserFarms_Users] FOREIGN KEY([UserID]) REFERENCES [dbo].[Users] ([ID]),
--	CONSTRAINT [FK_UserFarms_Farms] FOREIGN KEY([FarmID]) REFERENCES [dbo].[Farms] ([ID]),
--	CONSTRAINT [FK_UserFarms_Roles] FOREIGN KEY([RoleID]) REFERENCES [dbo].[Roles] ([ID])
--)
